### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by andrewbird**

### CODE REVIEW

**Comment by andrewbird** [comment]
I can't decide whether it should be `license` or `LICENSE`, so closing for now until I get some inspiration, or advice!

**Comment by PerditionC** [comment]
All caps no extension or all lowercase with.txt extension.  1st works better on GitHub, 2nd better on windows

**Comment by andrewbird** [comment]
Thanks, I'll redo in a while to LICENSE

**Comment by andrewbird** [comment]
Thanks, for the info. I've updated it now.

**Pull request merged**
